# Python Basic 3
# This code is run on local laptop

In [1]:
with open("sampleio.txt","r") as file1:
    filestuff = file1.read()
    print(filestuff)

This is line 1
This is line 2
This is line 3
This is line 4




In [7]:
with open("sampleio.txt","r") as file1:
    lines = file1.readlines()
    print(lines)

['This is line 1\n']


In [11]:
with open("sampleio.txt","r") as file1:
    line = file1.readline()
    print(line)
    line = file1.readline()
    print(line)

This is line 1

This is line 2



In [13]:
with open("sampleio.txt","r") as file1:
    for line in file1:
        print(line)

This is line 1

This is line 2

This is line 3

This is line 4





In [15]:
with open("outputfile.txt","w") as file1:
    file1.write("Output line 1\n")
    file1.write("Output line 2\n")

In [16]:
mylist = ["Hallo", "Hai","Apa kabar", "semua"]
with open("outputfile2.txt","w") as file1:
    for l in mylist:
        file1.write(l)
        file1.write("\n")

In [19]:
mylist = ["Hallo", "Hai","Apa kabar", "semua"]
with open("outputfile2.txt","w") as file1:
    for l in mylist:
        file1.write(l)
        file1.write("\n")

In [20]:
mylist = ["Ini", "Kelas","DTS", "Data Science"]
with open("outputfile2.txt","a") as file1:
    for l in mylist:
        file1.write(l)
        file1.write("\n")

In [21]:
import pandas as pd
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")
df.head()


age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]

In [22]:
df.ix[1,2]

/home/anwar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/home/anwar/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]


7861.0

In [23]:
df.ix[1:5,3:7]

/home/anwar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/home/anwar/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


diabetes  ejection_fraction  high_blood_pressure  platelets
1         0                 38                    0  263358.03
2         0                 20                    0  162000.00
3         0                 20                    0  210000.00
4         1                 20                    0  327000.00
5         0                 40                    1  204000.00

In [24]:
df.to_csv('newdf.csv')

In [1]:
list1 = [1,2,3,4,5,6,7,8,9]

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array(list1)

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = arr2 * 2
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
type(arr1)

numpy.ndarray

In [12]:
arr1.dtype
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
4
(4,)


In [13]:
arr2[2:5]

array([3, 4, 5])

In [14]:
arr2[2:5] = 7,8,9

In [15]:
arr2

array([1, 2, 7, 8, 9, 6, 7, 8, 9])

In [16]:
u = arr1
v = np.array([3,4,5,6])
print(u)
print(v)

[1 2 3 4]
[3 4 5 6]


In [17]:
u+v

array([ 4,  6,  8, 10])

In [18]:
u-v

array([-2, -2, -2, -2])

In [21]:
u*2

array([2, 4, 6, 8])

In [22]:
z = []
for n,m in zip(u,v):
    z.append([n,m])

In [23]:
z

[[1, 3], [2, 4], [3, 5], [4, 6]]

In [25]:
type(z)
z = np.array(z)

In [26]:
z

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [27]:
print(z.ndim)
print(z.size)
print(z.shape)

2
8
(4, 2)


In [28]:
x =  np.dot(u,v)

In [29]:
x

50

In [31]:
z

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [33]:
w = np.array([[1,2,3],[4,5,6]])
w

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
r = np.dot(z,w)
r

array([[13, 17, 21],
       [18, 24, 30],
       [23, 31, 39],
       [28, 38, 48]])

In [35]:
z = []
y = np.array([1,2])
for n,m in zip(u,y):
    z.append([n,m])

In [36]:
z

[[1, 1], [2, 2]]